#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CookingApplication.Resource", IsApplication=true)]

namespace CookingApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f030000
			public const int fade_out = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int slide_right = 2130903041;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int Soup = 2131034112;
			
			// aapt resource value: 0x7f050014
			public const int advanced_search = 2131034132;
			
			// aapt resource value: 0x7f050017
			public const int btnBack = 2131034135;
			
			// aapt resource value: 0x7f050012
			public const int category = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int country = 2131034131;
			
			// aapt resource value: 0x7f050006
			public const int country1 = 2131034118;
			
			// aapt resource value: 0x7f050011
			public const int country10 = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int country2 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int country3 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int country4 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int country5 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int country6 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int country7 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int country8 = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int country9 = 2131034128;
			
			// aapt resource value: 0x7f050004
			public const int dessert = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int drink = 2131034117;
			
			// aapt resource value: 0x7f050015
			public const int favorites = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int main_course = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int salad = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int snak = 2131034114;
			
			// aapt resource value: 0x7f050016
			public const int textView1 = 2131034134;
			
			// aapt resource value: 0x7f05000d
			public const int textView3 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int textView4 = 2131034127;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Category = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Country = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Main = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Title1 = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
