#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CookingApplication.Resource", IsApplication=true)]

namespace CookingApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_out = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_right = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060001
			public const int category_array = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int countryes_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int Soup = 2131165184;
			
			// aapt resource value: 0x7f070020
			public const int advanced_search = 2131165216;
			
			// aapt resource value: 0x7f070028
			public const int btnBack = 2131165224;
			
			// aapt resource value: 0x7f070026
			public const int buttonSearth = 2131165222;
			
			// aapt resource value: 0x7f07001e
			public const int category = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int country = 2131165215;
			
			// aapt resource value: 0x7f070008
			public const int country1 = 2131165192;
			
			// aapt resource value: 0x7f07001c
			public const int country10 = 2131165212;
			
			// aapt resource value: 0x7f07000a
			public const int country2 = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int country3 = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int country4 = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int country5 = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int country6 = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int country7 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int country8 = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int country9 = 2131165210;
			
			// aapt resource value: 0x7f070004
			public const int dessert = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int drink = 2131165189;
			
			// aapt resource value: 0x7f070021
			public const int favorites = 2131165217;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout1 = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout2 = 2131165196;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout3 = 2131165201;
			
			// aapt resource value: 0x7f070016
			public const int linearLayout4 = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int linearLayout5 = 2131165209;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout6 = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int main_course = 2131165187;
			
			// aapt resource value: 0x7f070025
			public const int multiAutocomplete_country = 2131165221;
			
			// aapt resource value: 0x7f070001
			public const int salad = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int snak = 2131165186;
			
			// aapt resource value: 0x7f070024
			public const int spinner_Category = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int spinner_Country = 2131165219;
			
			// aapt resource value: 0x7f070009
			public const int textView1 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int textView2 = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int textView3 = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int textView4 = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int textView5 = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int textView6 = 2131165205;
			
			// aapt resource value: 0x7f07001b
			public const int textView7 = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int textView8 = 2131165213;
			
			// aapt resource value: 0x7f070022
			public const int textViewMAKET = 2131165218;
			
			// aapt resource value: 0x7f070027
			public const int textViewTitle = 2131165223;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Category = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Country = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Maket = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Preview = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Search = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Title1 = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
