#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CookingApplication.Resource", IsApplication=true)]

namespace CookingApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f030000
			public const int fade_out = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int slide_right = 2130903041;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int category_array = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int countryes_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int Soup = 2131099648;
			
			// aapt resource value: 0x7f060020
			public const int advanced_search = 2131099680;
			
			// aapt resource value: 0x7f060025
			public const int btnBack = 2131099685;
			
			// aapt resource value: 0x7f06001e
			public const int category = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int country = 2131099679;
			
			// aapt resource value: 0x7f060008
			public const int country1 = 2131099656;
			
			// aapt resource value: 0x7f06001c
			public const int country10 = 2131099676;
			
			// aapt resource value: 0x7f06000a
			public const int country2 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int country3 = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int country4 = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int country5 = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int country6 = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int country7 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int country8 = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int country9 = 2131099674;
			
			// aapt resource value: 0x7f060004
			public const int dessert = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int drink = 2131099653;
			
			// aapt resource value: 0x7f060021
			public const int favorites = 2131099681;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout1 = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout2 = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int linearLayout3 = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int linearLayout4 = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int linearLayout5 = 2131099673;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout6 = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int main_course = 2131099651;
			
			// aapt resource value: 0x7f060024
			public const int multiAutocomplete_country = 2131099684;
			
			// aapt resource value: 0x7f060001
			public const int salad = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int snak = 2131099650;
			
			// aapt resource value: 0x7f060022
			public const int spinner1 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int spinner2 = 2131099683;
			
			// aapt resource value: 0x7f060009
			public const int textView1 = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int textView2 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int textView3 = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int textView4 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int textView5 = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int textView6 = 2131099669;
			
			// aapt resource value: 0x7f06001b
			public const int textView7 = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int textView8 = 2131099677;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Category = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Country = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Main = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Search = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Title1 = 2130837508;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
